name: RunDanger

on:
  pull_request:
    branches: [ develop ]

jobs:
  rundanger:
    
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install danger
      run: brew install danger/tap/danger-swift
    - name: GO Danger
      run: danger-swift ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
