name: Swift

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install bundle
      run: bundle install
    - name: Update bundler
      run: bundle update --bundler
    - name: Install xcbeautify
      run: brew install xcbeautify
    - name: Run tests
      run: bundle exec fastlane testLane
